### ISSUE TITLE
Chrome overlay page

### ISSUE THREAD

**Issue by mmmiazhou** [YuxinZhou2/mindful#2]
Issues related to the page that's being displayed when the use tries to access a blocked website

**Comment by KamyMouss** [comment]
- 1 Question + 4 answer choices 
- When answered right, 3 buttons popup below: “Close tab”, “Another question”, “Access website”
- When answered wrong, 3 buttons popup below: “Try again”, “Access website”, “Close tab”
- Redirection to website (popup disappearing)
